core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls')),
    path(
        'reset_password/', 
        auth_views.PasswordResetView.as_view(template_name='users/reset_password.html'),
        name='reset_password'),
    path(
        'reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name='users/reset_password_done.html'), 
        name='password_reset_done'),
    path(
        'reset/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), 
        name='password_reset_confirm'),
    path(
        'reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), 
        name='password_reset_complete'),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projects/urls.py
from django.urls import path

from . import views


app_name = 'projects'
urlpatterns = [
    path('', views.ProjectIndexView.as_view(), name='index'),
    path('project/<str:pk>/', views.project_detail, name='detail'),
    path('create-project/', views.createproject, name='create-project'),
    path('update-project/<str:p_uuid>/', views.updateproject, name='update-project'),
    path('delete-project/<str:p_uuid>/', views.deleteproject, name='delete-project'),
]

users/urls.py
from django.urls import path

from . import views


app_name = 'users'
urlpatterns = [
    path('', views.all_profiles, name='profiles'),
    path('profile/<slug:pk>/', views.single_profile, name='single_profile'),

    # user authentication
    path('login_user/', views.login_user, name='login_user'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('register_user/', views.register_user, name='register_user'),

    # user account
    path('user_account/', views.user_account, name='user_account'),
    path('edit_account/', views.edit_account, name='edit_account'),

    # user skills
    path('add_skill/', views.add_skill, name='add_skill'),
    path('update_skill/<slug:pk>/', views.update_skill, name='update_skill'),
    path('delete_skill/<slug:pk>/', views.delete_skill, name='delete_skill'),  

    # user messages
    path('inbox/', views.inbox, name='inbox'),
    path('message/<slug:pk>/', views.single_message, name='single_message'),
    path('send-message/<slug:recipient_pk>', views.send_message, name='send_message'),
]

projects/models.py
from django.db import models
import uuid

from users.models import Profile


class Project(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    image = models.ImageField(default='default.jpg')
    demo_link = models.CharField(max_length=2000, blank=True)
    source_link = models.CharField(max_length=2000, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, primary_key=True,
                          editable=False, unique=True)

    class Meta:
        ordering = ['-vote_ratio', 'vote_total', 'title']
    
    def __str__(self):
        return self.title

    @property
    def reviewers(self):
        all_reviewers = self.review_set.all().values_list('owner__id', flat=True)
        return all_reviewers


    @property
    def refresh_votes(self):
        reviews = self.review_set.all()
        up_votes = reviews.filter(value='up').count()
        total_votes = reviews.count()
        ratio = (up_votes / total_votes) * 100
        self.vote_ratio = ratio
        self.vote_total = total_votes
        self.save()




class Review(models.Model):
    VOTE_TYPE = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote')
    )
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)
    
    class Meta:
        unique_together = [['owner', 'project']]
    
    def __str__(self):
        return self.value


class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, primary_key=True,
                          editable=False, unique=True)
    
    def __str__(self):
        return self.name

users/models.py
import uuid

from django.db import models
from django.contrib.auth.models import User



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, blank=True)
    username = models.CharField(max_length=200, blank=True)
    location = models.CharField(max_length=200, blank=True)
    email = models.EmailField()
    short_intro = models.CharField(max_length=200, blank=True)
    bio = models.TextField(blank=True)
    profile_image = models.ImageField(default='users/default_profile.png', upload_to='users/profiles/')
    social_twitter = models.URLField(blank=True)
    social_linkedin = models.URLField(blank=True)
    social_youtube = models.URLField(blank=True)
    social_website = models.URLField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, editable=False, primary_key=True)

    def __str__(self):
        return str(self.username)


class Skill(models.Model):
    id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, primary_key=True)
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Message(models.Model):
    sender = models.ForeignKey(
        Profile, 
        on_delete=models.SET_NULL, 
        null=True, blank=True, 
        related_name='sender_messages')

    recipient = models.ForeignKey(
        Profile, 
        on_delete=models.SET_NULL, 
        null=True, blank=True, 
        related_name='recipient_messages')
    
    name = models.CharField(max_length=200, blank=True)
    email = models.EmailField(blank=True)
    subject = models.CharField(max_length=200, blank=True)
    body = models.TextField()
    is_read = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, editable=False, primary_key=True)

    class Meta:
        ordering = ['is_read', '-created']

    def __str__(self):
        return self.subject

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Skill, Message


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'email', 'username', 'password1', 'password2']
        labels = {
            'first_name': 'Name'
        }


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']

    
class SkillForm(ModelForm):
    class Meta:
        model = Skill
        exclude = ['owner']


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['name', 'email', 'subject', 'body']

users/views.py
from django.shortcuts import redirect, render
from django.shortcuts import get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from .models import Profile, Message
from .forms import CustomUserCreationForm, ProfileForm, SkillForm, MessageForm


def my_paginator(request, query_set):
    requested_page_num = request.GET.get('page')
    paginator_obj = Paginator(query_set, per_page=6)
    try:
        page = paginator_obj.page(requested_page_num)
    except PageNotAnInteger:
        page = paginator_obj.page(number=1)
    except EmptyPage:
        page_num = paginator_obj.num_pages
        page = paginator_obj.page(number=page_num)
    
    start_index = page.number - 2
    if start_index < 1:
        start_index = 1

    end_index = page.number + 2
    if end_index > paginator_obj.num_pages:
        end_index = paginator_obj.num_pages

    page_range = range(start_index, end_index+1)

    return page, page_range


def all_profiles(request):
    search_query = request.GET.get('search_query') or ''

    if search_query:
        profiles = Profile.objects.filter(
            Q(name__icontains=search_query) |
            Q(short_intro__icontains=search_query) |
            Q(skill__name__iexact=search_query)
        ).distinct()

    else:
        profiles = Profile.objects.all()
    
    # pagination the profiles
    profiles, page_range = my_paginator(request, profiles)

    context = {
        'profiles': profiles,
        'search_query': search_query,
        'page_range': page_range
    }
    return render(request, 'users/profiles.html', context)


def single_profile(request, pk):
    profile = get_object_or_404(Profile, id=pk)

    top_skills = profile.skill_set.exclude(description='')
    other_skills = profile.skill_set.filter(description='')
    context = {
        'profile': profile,
        'top_skills': top_skills,
        'other_skills': other_skills
    }
    return render(request, 'users/single_profile.html', context)


def login_user(request):
    if request.user.is_authenticated:
        return redirect('users:profiles')

    if request.method == 'POST':
        uname = request.POST['username']
        upwd = request.POST['password']
        try:
            User.objects.get(username=uname)
        except User.DoesNotExist:
            messages.error(request, "Username does not exist!")
            return redirect('users:login_user')
        
        user = authenticate(request, username=uname, password=upwd)
        if user:
            login(request, user)
            return redirect(request.GET['next'] if 'next' in request.GET else 'users:user_account')
        else:
            messages.error(request, 'Username or password is incorrect')
            return redirect('users:login_user')

    context = {'page': 'login'}
    return render(request, 'users/login_register.html', context)


def logout_user(request):
    if request.user.is_authenticated:
        logout(request)
        messages.error(request, 'User was logged out!')
        return redirect('users:login_user')


def register_user(request):
    form = CustomUserCreationForm()

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            messages.success(request, "User account was created!")
            return redirect('users:edit_account')
        else:
            messages.error(request, 'An error occurred during registration')

    context = {'page': 'register', 'form': form}
    return render(request, 'users/login_register.html', context)


@login_required(login_url='users:login_user')
def user_account(request):
    profile = request.user.profile
    context = {'profile': profile}
    return render(request, 'users/account.html', context)


@login_required(login_url='users:login_user')
def edit_account(request):
    profile = request.user.profile
    form = ProfileForm(instance=profile)
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=profile, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Updated Successfuly!")
            return redirect('users:user_account')
        else:
            messages.error(request, 'Your form is not valid!')
    
    context = {'form': form}
    return render(request, 'users/edit_profile.html', context)


@login_required(login_url='users:login_user')
def add_skill(request):
    if request.method == 'POST':
        form = SkillForm(request.POST)
        if form.is_valid():
            skill = form.save(commit=False)
            profile = request.user.profile
            skill.owner = profile
            skill.save()

            messages.success(request, 'skill added successfuly!')
            return redirect('users:user_account')

        else:
            messages.error(request, 'Your form is not valid!')

    form = SkillForm()
    conetxt = {'form': form}
    return render(request, 'users/skill_form.html', conetxt)


@login_required(login_url='users:login_user')
def update_skill(request, pk):
    profile = request.user.profile
    skill = get_object_or_404(profile.skill_set, id=pk)
    form = SkillForm(instance=skill)
    if request.method == 'POST':
        form = SkillForm(request.POST, instance=skill)
        if form.is_valid():
            form.save()
            messages.success(request, 'Skill Updated successfuly!')
            return redirect('users:user_account')
        else:
            messages.error(request, 'Your form is not valid!')

    context = {'form': form}
    return render(request, 'users/skill_form.html', context)


@login_required(login_url='users:login_user')
def delete_skill(request, pk):
    profile = request.user.profile
    skill = get_object_or_404(profile.skill_set, id=pk)
    if request.method == 'POST':
        skill.delete()
        messages.success(request, 'the "{}" skill deleted'.format(skill.name))
        return redirect('users:user_account')

    context = {'skill': skill}
    return render(request, 'users/delete_skill.html', context)


@login_required(login_url='users:login_user')
def inbox(request):
    profile = request.user.profile
    all_messages = profile.recipient_messages.all()
    unread_count = all_messages.filter(is_read=False).count()

    context = {'all_messages': all_messages, 'unread_count': unread_count}
    return render(request, 'users/inbox.html', context)


@login_required(login_url='users:login_user')
def single_message(request, pk):
    user_messages = request.user.profile.recipient_messages.all()
    requested_message = get_object_or_404(user_messages, id=pk)
    if requested_message.is_read == False:
        requested_message.is_read = True
        requested_message.save()
    
    context = {'message': requested_message}
    return render(request, 'users/message.html', context)


def send_message(request, recipient_pk):
    recipient = get_object_or_404(Profile, id=recipient_pk)
    form = MessageForm()
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            message_obj = form.save(commit=False)
            if request.user.is_authenticated:
                message_obj.sender = request.user.profile
                message_obj.name = request.user.profile.name
                message_obj.email = request.user.profile.email
            
            message_obj.recipient = recipient
            message_obj.save()
            # show the success message
            messages.success(request, 'message sent successfuly!')
            return redirect('users:single_profile', recipient_pk)
        
        else:
            messages.error(request, 'Something is worng!')
            
    context = {'form': form, 'recipient_id': recipient.id}
    return render(request, 'users/messageform.html', context)

users/templates/users/account.html
{% extends 'main.html' %}

{% block content %}
  <!-- Main Section -->
  <main class="settingsPage profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'users:edit_account' %}"><i class="im im-edit"></i> Edit</a>
              <img class="avatar avatar--xl" src="{{ profile.profile_image.url }}" />
              <h2 class="dev__name">{{ profile.name }}</h2>
              <p class="dev__title">{{ profile.short_intro }}</p>
              <p class="dev__location">Based in {{ profile.location }}</p>
              <ul class="dev__social">

                {% if profile.social_github %}
                <li>
                  <a title="Github" href="{{ profile.social_github }}" target="_blank"><i class="im im-github"></i></a>
                </li>
                {% endif %}

                {% if profile.social_twitter %}
                <li>
                  <a title="Twitter" href="{{ profile.social_twitter }}" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                {% endif %}

                {% if profile.social_linkedin %}
                <li>
                  <a title="LinkedIn" href="{{ profile.social_linkedin }}" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                {% endif %}                

                {% if profile.social_website %}
                <li>
                  <a title="Personal Website" href="{{ profile.social_website }}" target="_blank"><i class="im im-globe"></i></a>
                </li>
                {% endif %}

              </ul>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
              {{ profile.bio }}
            </p>
          </div>
          <div class="settings">
            <h3 class="settings__title">Skills</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'users:add_skill' %}"><i class="im im-plus"></i> Add Skill</a>
          </div>

          <table class="settings__table">
            {% for skill in profile.skill_set.all %}
            <tr>
              <td class="settings__tableInfo">
                <h4>{{ skill.name }}</h4>
                <p>{{ skill.description }}</p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'users:update_skill' pk=skill.id %}"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'users:delete_skill' pk=skill.id %}?next=/user_account/"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
            {% endfor %}
          </table>

          <div class="settings">
            <h3 class="settings__title">Projects</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'projects:create-project' %}"><i class="im im-plus"></i> Add Project</a>
          </div>

          <table class="settings__table">
            {% for project in profile.project_set.all %}
            <tr>
              <td class="settings__thumbnail">
                <a href="{% url 'projects:detail' pk=project.id %}"><img src="{{ project.image.url }}" alt="Project Thumbnail" /></a>
              </td>
              <td class="settings__tableInfo">
                <a href="{% url 'projects:detail' pk=project.id %}">{{ project.title }}</a>
                <p>{{ project.description|truncatechars:150 }}</p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'projects:update-project' p_uuid=project.id %}"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'projects:delete-project' p_uuid=project.id %}?next=/user_account/"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
            {% endfor %}
          </table>

        </div>
      </div>
    </div>
  </main>
{% endblock content %}

users/templates/users/delete_skill.html
{% extends 'main.html' %}


{% block content %}
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="{{ request.GET.next }}"><i class="im im-angle-left"></i></a>
                <br>

                <form action="" method="post">
                    {% csrf_token %}
                    <p>Do you want to delete the skill that name is {{ skill }}</p>
                    <a class="btn btn--sub btn--lg  my-md" href="{{ request.GET.next }}">No</a>
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Yes" />
                </form>
            </div>
        </div>
    </main>
{% endblock content %}

users/templates/users/edit_profile.html
{% extends 'main.html' %}


{% block content %}
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="{% url 'users:user_account' %}"><i class="im im-angle-left"></i></a>
                <br>

                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    
                    {% for field in form %}
                    <div class="form__field">
                        <label for="formInput#text">{{ field.label }}</label>
                        {{ field }}
                    </div>
                    {% endfor %}
                    
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>
{% endblock content %}

users/templates/users/inbox.html
{% extends 'main.html' %}

{% block content %}
<main class="inbox my-xl">
    <div class="content-box">
      <h3 class="inbox__title">New Messages(<span>{{ unread_count }}</span>)</h3>
      <ul class="messages">
        {% for message in all_messages %}
        <li class="message {% if not message.is_read %} message--unread {% endif %}">
          <a href="{% url 'users:single_message' pk=message.id %}">
            <span class="message__author">{{ message.name }}</span>
            <span class="message__subject">{{ message.subject }}</span>
            <span class="message__date">{{ message.created }}</span>
          </a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </main>
{% endblock %}

users/templates/users/login_register.html
{% extends 'main.html' %}


{% block content %}

    {% if page == 'login' %}
        <div class="auth">
            <div class="card">
              <div class="auth__header text-center">
                <!-- <a href="/">
                  <img src="" alt="icon"/>
                </a> -->
                <h3>Account Login</h3>
                <p>Hello Developer, Welcome Back!</p>
              </div>
      
              <form action="" method="post" class="form auth__form">
                {% csrf_token %}
                <!-- Input:Username -->
                <div class="form__field">
                  <label for="formInput#text">Username: </label>
                  <input
                    class="input input--text"
                    id="formInput#text"
                    type="text"
                    name="username"
                    placeholder="Enter your username..."
                  />
                </div>
      
                <!-- Input:Password -->
                <div class="form__field">
                  <label for="formInput#password">Password: </label>
                  <input
                    class="input input--password"
                    id="formInput#passowrd"
                    type="password"
                    name="password"
                    placeholder="••••••••"
                  />
                </div>
                <div class="auth__actions">
                  <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
                  <a href="{% url 'reset_password' %}">Forget Password?</a>
                </div>
              </form>
              <div class="auth__alternative">
                <p>Don't have an Account?</p>
                <a href="{% url 'users:register_user' %}">Sign Up</a>
              </div>
            </div>
        </div>

    {% else %}
    
        <div class="auth">
            <div class="card">
              <div class="auth__header text-center">
                <!-- <a href="/">
                  <img src="images/icon.svg" alt="icon" />
                </a> -->
                <h3>Register an Account</h3>
                <p>Create a new developer account</p>
              </div>
      
              <form action="{% url 'users:register_user' %}" method="post" class="form auth__form">
                {% csrf_token %}

                {% for field in form %}
                    <div class="form__field">
                        <label for="formInput#text">{{ field.label}}</label>
                        {{ field }}
                    </div>

                    {% if field.errors %}
                      {% for error in field.errors %}
                      <p style="color: red;">{{ error }}</p>
                      {% endfor %}
                    {% endif %}

                {% endfor %}


                <div class="auth__actions">
                  <input class="btn btn--sub btn--lg" type="submit" value="Sign  In" />
                </div>
              </form>
              <div class="auth__alternative">
                <p>Already have an Account?</p>
                <a href="{% url 'users:login_user' %}">Log In</a>
              </div>
            </div>
        </div>

    {% endif %}

{% endblock content %}

users/templates/users/message.html
{% extends 'main.html' %}

{% block content %}
<main class="messagePage my-xl">
    <div class="content-box">
      <div class="message">
        <a class="backButton" href="{% url 'users:inbox' %}"><i class="im im-angle-left"></i></a>
        <h2 class="message__subject">{{ message.subject }}</h4>
          <a href="profile.html" class="message__author">{{ message.name }}</a>
          <p class="message__date">{{ message.created }}</p>
          <div class="message__body">
            {{ message.body }}
          </div>
      </div>
    </div>
  </main>
{% endblock %}

users/templates/users/single_profile.html
{% extends 'main.html' %}

{% block content %}
    <!-- Main Section -->
  <main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{ profile.profile_image.url }}" />
              <h2 class="dev__name">{{ profile.name }}</h2>
              <p class="dev__title">{{ profile.short_intro }}</p>
              <p class="dev__location">Based in {{ profile.location }}</p>
              <ul class="dev__social">

                {% if profile.social_github %}
                <li>
                  <a title="Github" href="{{ profile.social_github }}" target="_blank"><i class="im im-github"></i></a>
                </li>
                {% endif %}

                {% if profile.social_twitter %}
                <li>
                  <a title="Twitter" href="{{ profile.social_twitter }}" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                {% endif %}

                {% if profile.social_linkedin %}
                <li>
                  <a title="LinkedIn" href="{{ profile.social_linkedin }}" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                {% endif %}                

                {% if profile.social_website %}
                <li>
                  <a title="Personal Website" href="{{ profile.social_website }}" target="_blank"><i class="im im-globe"></i></a>
                </li>
                {% endif %}

              </ul>
              {% if profile.id != request.user.profile.id %}
              <a href="{% url 'users:send_message' recipient_pk=profile.id %}" class="btn btn--sub btn--lg">Send Message </a>
              {% endif %}
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
              {{ profile.bio }}
            </p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
            <div class="devInfo__skills">
            {% for skill in top_skills %}
              <div class="devSkill">
                <h4 class="devSkill__title">{{ skill.name }}</h4>
                <p class="devSkill__info">
                  {{ skill.description }}
                </p>
              </div>
            {% endfor %}

              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">
              {% for skill in other_skills %}
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>{{ skill.name }}</small>
                </span>
              {% endfor %}
              </div>
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">
            {% for project in profile.project_set.all %}
              <div class="column">
                <div class="card project">
                  <a href="{% url 'projects:detail' pk=project.id %}" class="project">
                    <img class="project__thumbnail" src="{{ project.image.url }}" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{ project.title }}</h3>
                      <p><a class="project__author" href="">By {{ profile.name }}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{ project.vote_ratio }}%</span> Postitive
                        Feedback ({{ project.vote_total }} Vote{{ project.vote_total|pluralize:'s' }})
                      </p>
                      <div class="project__tags">
                      {% for tag in project.tags.all %}
                        <span class="tag tag--pill tag--main">
                          <small>{{ tag.name }}</small>
                        </span>
                      {% endfor %}
                      </div>
                    </div>
                  </a>
                </div>
              </div>
            {% endfor %}

            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock content %}