core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls')),
    path(
        'reset_password/', 
        auth_views.PasswordResetView.as_view(template_name='users/reset_password.html'),
        name='reset_password'),
    path(
        'reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name='users/reset_password_done.html'), 
        name='password_reset_done'),
    path(
        'reset/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), 
        name='password_reset_confirm'),
    path(
        'reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), 
        name='password_reset_complete'),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projects/urls.py
from django.urls import path

from . import views


app_name = 'projects'
urlpatterns = [
    path('', views.ProjectIndexView.as_view(), name='index'),
    path('project/<str:pk>/', views.project_detail, name='detail'),
    path('create-project/', views.createproject, name='create-project'),
    path('update-project/<str:p_uuid>/', views.updateproject, name='update-project'),
    path('delete-project/<str:p_uuid>/', views.deleteproject, name='delete-project'),
]

users/urls.py
from django.urls import path

from . import views


app_name = 'users'
urlpatterns = [
    path('', views.all_profiles, name='profiles'),
    path('profile/<slug:pk>/', views.single_profile, name='single_profile'),

    # user authentication
    path('login_user/', views.login_user, name='login_user'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('register_user/', views.register_user, name='register_user'),

    # user account
    path('user_account/', views.user_account, name='user_account'),
    path('edit_account/', views.edit_account, name='edit_account'),

    # user skills
    path('add_skill/', views.add_skill, name='add_skill'),
    path('update_skill/<slug:pk>/', views.update_skill, name='update_skill'),
    path('delete_skill/<slug:pk>/', views.delete_skill, name='delete_skill'),  

    # user messages
    path('inbox/', views.inbox, name='inbox'),
    path('message/<slug:pk>/', views.single_message, name='single_message'),
    path('send-message/<slug:recipient_pk>', views.send_message, name='send_message'),
]

projects/models.py
from django.db import models
import uuid

from users.models import Profile


class Project(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    image = models.ImageField(default='default.jpg')
    demo_link = models.CharField(max_length=2000, blank=True)
    source_link = models.CharField(max_length=2000, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, primary_key=True,
                          editable=False, unique=True)

    class Meta:
        ordering = ['-vote_ratio', 'vote_total', 'title']
    
    def __str__(self):
        return self.title

    @property
    def reviewers(self):
        all_reviewers = self.review_set.all().values_list('owner__id', flat=True)
        return all_reviewers


    @property
    def refresh_votes(self):
        reviews = self.review_set.all()
        up_votes = reviews.filter(value='up').count()
        total_votes = reviews.count()
        ratio = (up_votes / total_votes) * 100
        self.vote_ratio = ratio
        self.vote_total = total_votes
        self.save()




class Review(models.Model):
    VOTE_TYPE = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote')
    )
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)
    
    class Meta:
        unique_together = [['owner', 'project']]
    
    def __str__(self):
        return self.value


class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, primary_key=True,
                          editable=False, unique=True)
    
    def __str__(self):
        return self.name

projects/forms.py
from django import forms
from django.forms import ModelForm
from django import forms
from .models import Project, Review



class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'description', 'image', 'demo_link', 'source_link', 'tags']

        widgets = {
            'tags': forms.CheckboxSelectMultiple(),
        }


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['value', 'body']
        labels = {
            'value': 'Place your vote',
            'body': 'Add a comment with your vote'
        }

projects/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib import messages

from projects.models import Project
from .forms import ProjectForm, ReviewForm


class ProjectIndexView(generic.ListView):
    model = Project
    paginate_by = 6
    template_name = 'projects/index.html'

    def get_queryset(self, *args, **kwargs):
        search_query = self.request.GET.get('search_query')
        if search_query:
            projects = Project.objects.filter(
                Q(title__icontains=search_query) |
                Q(description__icontains=search_query) |
                Q(owner__name__icontains=search_query) |
                Q(tags__name__icontains=search_query)
            ).distinct()
            return projects
        else:
            projects = super().get_queryset(*args, **kwargs)
            return projects

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['search_query'] = self.request.GET.get('search_query') or ''
        return context



def project_detail(request, pk):
    project = get_object_or_404(Project, id=pk)
    form = ReviewForm()

    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review_obj = form.save(commit=False)
            review_obj.owner = request.user.profile
            review_obj.project = project
            review_obj.save()
            project.refresh_votes
            messages.success(request, 'Your review successfully added!')
            return redirect('projects:detail', pk=pk)


    context = {
        'project': project,
        'form': form
    }
    return render(request, 'projects/project_detail.html', context)



@login_required(login_url='users:login_user')
def createproject(requeset):
    form = ProjectForm()

    if requeset.method == "POST":
        form = ProjectForm(requeset.POST, files=requeset.FILES)
        if form.is_valid():
            profile = requeset.user.profile
            project = form.save(commit=False)
            project.owner = profile
            project.save()
            return redirect('users:user_account')

    context = {
        'form': form
    }

    return render(requeset, 'projects/project_form.html', context)


@login_required(login_url='users:login_user')
def updateproject(request, p_uuid):
    profile = request.user.profile
    project = get_object_or_404(profile.project_set, id=p_uuid)
    form = ProjectForm(instance=project)

    if request.method == "POST":
        form = ProjectForm(request.POST, files=request.FILES, instance=project)
        if form.is_valid():
            form.save()
            return redirect('users:user_account')

    context = {
        'form': form
    }
    return render(request, 'projects/project_form.html', context)


@login_required(login_url='users:login_user')
def deleteproject(request, p_uuid):
    profile = request.user.profile
    project = get_object_or_404(profile.project_set, id=p_uuid)
    if request.method == "POST":
        project.delete()
        return redirect('users:user_account')

    context = {
        'project': project
    }
    return render(request, 'projects/delete_project.html', context)

projects/templates/projects/delete_project.html
{% extends 'main.html' %}

{% block content %}
    <h2>Delete the project:</h2>
    <p>Do you really want to delete the "{{ project.title }}"?</p>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit">
    </form>
    
{% endblock content %}

projects/templates/projects/index.html
{% extends 'main.html' %}

{% block content %}
  <!-- Main Section -->
  <main class="projects">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>Search for <span>Projects</span></h2>
        </div>

        <div class="hero-section__search">
          <form class="form" action="{% url 'projects:index' %}" method="get">
            <div class="form__field">
              <label for="formInput#search">Search By Projects </label>
              <input class="input input--text" id="formInput#search" type="text" name="search_query"
                placeholder="Search by Project Title" value="{{ search_query }}" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="projectsList">
      <div class="container">
        <div class="grid grid--three">

        {% for project in object_list %}
          <div class="column">
            <div class="card project">
              <a href="{% url 'projects:detail' project.id %}" class="project">
                <img class="project__thumbnail" src="{{ project.image.url }}" alt="project thumbnail" />
                <div class="card__body">
                  <h3 class="project__title">{{ project.title }}</h3>
                  <p><a class="project__author" href="{% url 'users:single_profile' pk=project.owner.id %}">{{ project.owner.username }}</a></p>
                  <p class="project--rating">
                    <span style="font-weight: bold;">{{ project.vote_ratio }}%</span> Postitive
                    Feedback ({{ project.vote_total }} Vote{{ project.vote_total|pluralize }})
                  </p>
                  <div class="project__tags">
                    {% for tag in project.tags.all %}
                      <span class="tag tag--pill tag--main">
                        <small>{{ tag.name }}</small>
                      </span>
                    {% endfor %}
                  </div>
                </div>
              </a>
            </div>
          </div>
        {% endfor %}

        </div>
      </div>
    </section>

    <!-- PAGINATION -->
    <div class="pagination">
      <ul class="container">
        {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}" class="btn">&#10094; Prev</a></li>
        {% else %}
        <li><a href="#" class="btn btn--disabled">&#10094; Prev</a></li>
        {% endif %}
        
        {% for i in page_obj.paginator.page_range %}
        <li><a href="?page={{ i }}" class="btn {% if page_obj.number == i %} btn--sub {% endif %}">{{ i }}</a></li>
        {% endfor %}

        {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}" class="btn">Next &#10095;</a></li>
        {% else %}
        <li><a href="" class="btn btn--disabled">Next &#10095;</a></li>
        {% endif %}
      </ul>
    </div>

  </main>
{% endblock content %}

projects/templates/projects/project_detail.html
{% extends 'main.html' %}

{% block content %}
<!-- Main Section -->
<main class="singleProject my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <h3 class="singleProject__subtitle">Tools & Stacks</h3>
          <div class="singleProject__toolStack">

            {% for tag in project.tags.all %}
            <span class="tag tag--pill tag--sub tag--lg">
              <small>{{ tag.name }}</small>
            </span>
            {% endfor %}

          </div>

          {% if project.source_link %}
          <a class="singleProject__liveLink" href="#" target="_blank"><i class="im im-external-link"></i>Source Code
          </a>
          {% endif %}

          <br>

          {% if project.demo_link %}
          <a class="singleProject__liveLink" href="#" target="_blank"><i class="im im-external-link"></i>Live Demo
          </a>
          {% endif %}

        </div>
        <div class="column column--2of3">
          <img class="singleProject__preview" src="{{ project.image.url }}" alt="portfolio thumbnail" />
          <a href="{% url 'users:single_profile' pk=project.owner.id %}" class="singleProject__developer">{{ project.owner.name }}</a>
          <h2 class="singleProject__title">{{ project.title }}</h2>
          <h3 class="singleProject__subtitle">About the Project</h3>
          <div class="singleProject__info">
            {{ project.description }}
          </div>

          <div class="comments">
            <h3 class="singleProject__subtitle">Feedback</h3>
            <h5 class="project--rating">
              {{ project.vote_ratio }}% Postitive Feedback ({{ project.vote_total }} Vote{{ project.vote_total|pluralize }})
            </h5>

            <!-- Review Form -->
            {% if not request.user.is_authenticated %}
              <p>You are not authenticated!</p>
              <a href="{% url 'users:login_user' %}?next={{ request.path }}">Let's authenticate</a>
            {% elif project.owner.id == request.user.profile.id %}
              <p>it's your project and you can't review this!</p>
            {% elif request.user.profile.id in project.reviewers %}
              <p>You already submit the review for this project!</p>
            {% else %}
              <form class="form" action="{% url 'projects:detail' pk=project.id %}" method="POST">
                {% csrf_token %}
                <div class="form__field">
                  {{ form.as_p }}
                </div>
                <input class="btn btn--sub btn--lg" type="submit" value="Comments" />
              </form>
            {% endif %}
            
            <!-- Reviews -->
            <div class="commentList">
              {% for comment in project.review_set.all %}
              {% if comment.body %}
              <div class="comment">
                <a href="{% url 'users:single_profile' pk=comment.owner.id %}">
                  <img class="avatar avatar--md"
                    src="{{ comment.owner.profile_image.url }}" alt="{{ comment.owner.username }}" />
                </a>
                <div class="comment__details">
                  <a href="{% url 'users:single_profile' pk=comment.owner.id %}" class="comment__author">{{ comment.owner.username }}</a>
                  <p class="comment__info">
                    {{ comment.body }}
                  </p>
                </div>
              </div>
              {% endif %}
              {% endfor %}
            </div>

          </div>
        </div>
      </div>
    </div>
    </div>
  </main>
{% endblock %}

projects/templates/projects/project_form.html
{% extends 'main.html' %}

{% block content %}
<!-- Main Section -->
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="#"><i class="im im-angle-left"></i></a>
            <br>

            <form class="form" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                <!-- Input:Text -->
                <div class="form__field">
                    <label for="formInput#text">{{ field.label }}</label>
                    {{ field }}
                </div>
                {% endfor %}
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock content %}