core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls')),
    path(
        'reset_password/', 
        auth_views.PasswordResetView.as_view(template_name='users/reset_password.html'),
        name='reset_password'),
    path(
        'reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name='users/reset_password_done.html'), 
        name='password_reset_done'),
    path(
        'reset/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), 
        name='password_reset_confirm'),
    path(
        'reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), 
        name='password_reset_complete'),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projects/urls.py
from django.urls import path

from . import views


app_name = 'projects'
urlpatterns = [
    path('', views.ProjectIndexView.as_view(), name='index'),
    path('project/<str:pk>/', views.project_detail, name='detail'),
    path('create-project/', views.createproject, name='create-project'),
    path('update-project/<str:p_uuid>/', views.updateproject, name='update-project'),
    path('delete-project/<str:p_uuid>/', views.deleteproject, name='delete-project'),
]

users/urls.py
from django.urls import path

from . import views


app_name = 'users'
urlpatterns = [
    path('', views.all_profiles, name='profiles'),
    path('profile/<slug:pk>/', views.single_profile, name='single_profile'),

    # user authentication
    path('login_user/', views.login_user, name='login_user'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('register_user/', views.register_user, name='register_user'),

    # user account
    path('user_account/', views.user_account, name='user_account'),
    path('edit_account/', views.edit_account, name='edit_account'),

    # user skills
    path('add_skill/', views.add_skill, name='add_skill'),
    path('update_skill/<slug:pk>/', views.update_skill, name='update_skill'),
    path('delete_skill/<slug:pk>/', views.delete_skill, name='delete_skill'),  

    # user messages
    path('inbox/', views.inbox, name='inbox'),
    path('message/<slug:pk>/', views.single_message, name='single_message'),
    path('send-message/<slug:recipient_pk>', views.send_message, name='send_message'),
]

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  
    <!-- Favicon -->
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
    <!-- Icon - IconMonster -->
    <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
    <!-- Mumble UI -->
    <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
    <!-- Dev Search UI -->
    <link rel="stylesheet" href="{% static 'styles/app.css' %}" />
  
    <title>DevSearch - Connect with Developers!</title>
</head>
<body>
    {% include 'navbar.html' %}

    {% if messages %}
        {% for message in messages %}
        <div class="alert alert--{{ message.tags }}">
            <p class="alert__message">{{ message }}</p>
        </div>
        {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock content %}
</body>
</html>

templates/navbar.html
{% load static %}

<header class="header">
    <div class="container container--narrow">
      <a href="{% url 'projects:index' %}" class="header__logo">
        <img src="{% static 'images/logo.png' %}" alt="DevSearch Logo" />
      </a>
      <nav class="header__nav">
        <input type="checkbox" id="responsive-menu" />
        <label for="responsive-menu" class="toggle-menu">
          <span>Menu</span>
          <div class="toggle-menu__lines"></div>
        </label>
        <ul class="header__menu">
          <li class="header__menuItem"><a href="{% url 'users:profiles' %}">Developers</a></li>
          <li class="header__menuItem"><a href="{% url 'projects:index' %}">Projects</a></li>

          {% if request.user.is_authenticated %}
          <li class="header__menuItem"><a href="{% url 'users:inbox' %}">Inbox</a></li>
          <li class="header__menuItem"><a href="{% url 'users:user_account' %}">Account</a></li>
          <li class="header__menuItem"><a href="{% url 'users:logout_user' %}" class="btn btn--sub">Logout</a></li>
          {% else %}
          <li class="header__menuItem"><a href="{% url 'users:login_user' %}" class="btn btn--sub">Login/Sign Up</a></li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </header>